<a href="https://colab.research.google.com/github/patidarparagi286-svg/machine-learning-concepts/blob/main/LabelEncoding(regr).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
from google.colab import files
uploaded= files.upload()
filename = list(uploaded.keys())[0]
df = pd.read_csv(filename)

Saving homeprices_new.csv to homeprices_new (1).csv

In [ ]:
df.head()

              town  area   price
0  monroe township  2600  550000
1  monroe township  3000  565000
2  monroe township  3200  610000
3  monroe township  3600  680000
4  monroe township  4000  725000

In [ ]:
df.tail()

            town  area   price
8   west windsor  3600  710000
9    robinsville  2600  575000
10   robinsville  2900  600000
11   robinsville  3100  620000
12   robinsville  3600  695000

In [ ]:
df.shape

(13, 3)

In [ ]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df['town']= le.fit_transform(df['town'])

In [ ]:
X=df.drop('price',axis=1)
y=df['price']
type(X)

pandas.core.frame.DataFrame

In [ ]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=0)

In [ ]:
model=LinearRegression()
model.fit(X_train,y_train)

LinearRegression()

In [ ]:
y_prd=model.predict(X_test)
y_prd

array([606750.90909091, 623989.09090909, 715485.45454545])

In [ ]:
y_test

6     615000
11    620000
4     725000
Name: price, dtype: int64

In [ ]:
y_prd

array([606750.90909091, 623989.09090909, 715485.45454545])

In [ ]:
from sklearn.metrics import r2_score
result= r2_score(y_test,y_prd)
print(result)

0.9773883038037953